version: "3.5"

services:
  shopping-cart-svc:
    image: "{REGISTRY}shopping-cart:${SHOPPING_CART_VERSION}"
    restart: always
    depends_on:
      - postgres-svc
    environment:
      PROFILE: ${PROFILE}
    ports:
      - 8002:8002

  postgres-svc:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBAdminPassword123!@#
    volumes:
      - /vm-disk/dir/:/var/lib/postgresql/postgres-data
    ports:
      - 9000:5432
